version: '3.3'

services:
  db:
    image: mysql/mysql-server:8.0
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demopass
      MYSQL_DATABASE: tako
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass

volumes:
  db_data: {}
