POST http://localhost:8080/comments
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTU3NzA4NDcsInVzZXJuYW1lIjoidGVzdDIifQ.ozXn6FShDH0Qw0OokLYos5vRosiDU2JKfY2dXGOaaao
Content-Type: application/json

{
   "postId": 9,
   "content": "Hello"
}

###
GET http://localhost:8080/comments
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTU3NzA4NDcsInVzZXJuYW1lIjoidGVzdDIifQ.ozXn6FShDH0Qw0OokLYos5vRosiDU2JKfY2dXGOaaao

###
GET http://localhost:8080/posts/9/comments
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTU3NzA4NDcsInVzZXJuYW1lIjoidGVzdDIifQ.ozXn6FShDH0Qw0OokLYos5vRosiDU2JKfY2dXGOaaao
