POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "test2",
  "password": "123",
  "email": "hungtin.bk15@gmail.com"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "test2",
  "password": "123"
}

###

GET http://localhost:8080/auth/confirm-code/da44a90b-f225-4dbf-bb09-01a6100e4be4

###
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
   "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwODc3NTMsInVzZXJuYW1lIjoidGVzdDIifQ.vBHn6dUVWRsqqs-NEO7Xbet1o_F20gxvAIVQZc8Yt9I"
}
